#mysql语句
查id:
  - select_list
  - select id from A.B where create_mobile={}
查用户id:
  - select_list
  - selecct id from A.B where mobile={}
查团队id:
  - select_list
  - select id from A.B where company_user_id=(select id from A.B where mobile={})
查C端用户id:
  - select_list
  - selecet id from A.B where mobile in({})
解除用户:
  - update
  - update A.B set status=2 where mobile={}
查询用户:

